test:
<%
case ENV.fetch('DATABASE', 'sqlite3mem')
when 'sqlite3'
%>
  adapter: <%= "jdbc" if defined? JRUBY_VERSION %>sqlite3
  database: db/combustion_test.sqlite
<% when 'sqlite3mem' %>
  adapter: <%= "jdbc" if defined? JRUBY_VERSION %>sqlite3
  database: ":memory:"
<% when 'postgresql' %>
  adapter: postgresql
  encoding: unicode
  database: groupify_test
  pool: 5
  username: postgres
  password: postgres
  min_messages: warning
<% when 'mysql' %>
  adapter: <%= defined?(JRUBY_VERSION) ? "jdbcmysql" : "mysql2" %>
  host: localhost
  username: root
  password:
  database: groupify_test
<% end %>
